apiVersion: v2
name: prometheus
description: Prometheus monitoring stack
type: application
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 55.5.0
    repository: https://prometheus-community.github.io/helm-charts
